# Please update your name and other info if you maintain or update this recipe
{% set ambertools_url = "http://ambermd.org/cgi-bin/AmberTools17-get.pl?Name=HaiNguyen&Institution=Rutgers&City=NewBrunswicks&State=NJ&Country=USA" %}
{% set version = "16" %}
{% set bugfix_version = "20" %} # applied update.1  to update.{{bugfix_version}}
{% set ambertools_version = version + '.' + bugfix_version %}
{% set ambertools_fn = "AmberTools" + version + ".tar.bz2" %}

# AMBER_BUILD_TASK = {'', 'ambermini', 'ambertools'}
{% if os.getenv('AMBER_BUILD_TASK', 'ambermini') == 'ambermini' %}
     {%set ambertools_package = 'ambermini101' %}
     {% set summary = "ambermini101, a subset of AmberTools" %}
{% else %}
     {%set ambertools_package = 'ambertools' %}
     {% set summary = "AmberTools is a set of programs for biomolecular simulation and analysis." %}
{% endif %}

package:
  name: {{ ambertools_package }}
  version: {{ ambertools_version }}

source:
  fn : {{ ambertools_fn }}
  url : {{ ambertools_url }}
  
  # Un-comment if using local path, must use file:/// if using tar file
  # url : file:///home/haichit/AmberTools17.tar.bz2
  # or
  # url : /home/haichit/amber17/

build:
  number: 1
  script_env:
    - AMBER_BUILD_TASK

requirements:
  build:
    - zlib
    - bzip2
    - python
    - mingwpy [win]
  run:
    - zlib
    - bzip2
    - python

about:
    home: https://ambermd.org
    license: GNU General Public License (GPL)
    summary: {{ summary }}
