#!/usr/bin/env python

import os
import sys
import subprocess

{update_prefix}

if sys.platform.startswith('linux'):
    os.environ['LD_LIBRARY_PATH'] = os.getenv('LD_LIBRARY_PATH', '') + ':' + prefix + '/lib'
nab_exe = os.path.join(prefix, 'bin', 'to_be_dispatched', 'nab')
commands = [nab_exe, ] + sys.argv[1:]
try:
    subprocess.call(commands)
except KeyboardInterrupt:
    pass
