# This file is a template, do not change it.
{% set version = "0" %}
{% set bugfix_version = "0" %} 
{% set build_number = "0" %}
{% set ambertools_version = version + '.' + bugfix_version %}
{% set ambertools_package = "ambertools_tempfile" %}
{% set summary = "AT_TMP, a temp tar file for building further" %}

package:
  name: {{ ambertools_package }}
  version: {{ ambertools_version }}

build:
  number: {{ build_number }}
  script_env:
    - AMBER_SRC

requirements:
  build:
    - libgcc [linux]
    - cython
    - numpy
    - python
  run:
    - libgcc [linux]
    - python
    - numpy

about:
    home: https://ambermd.org
    license: GNU General Public License (GPL)
    summary: {{ summary }}
