install:
	echo "hey"

python_serial:
	echo "python_serial"
	mkdir -p ../../lib/python2.7 || echo "hi"
	mkdir -p ../../lib/python3.4 || echo "hi"
	mkdir -p ../../lib/python3.5 || echo "hi"
	mkdir -p ../../lib/python3.6 || echo "hi"
