#!/usr/bin/env python

import os
import sys
import subprocess

os.environ['AMBERHOME'] = sys.prefix
antechamber_exe = os.path.join(sys.prefix, 'bin', '_antechamber')
try:
    subprocess.call(commands)
except KeyboardInterrupt:
    pass
