#!/usr/bin/env python

import os
import sys
import subprocess

os.environ['AMBERHOME'] = sys.prefix
if sys.platform.startswith('linux'):
    os.environ['LD_LIBRARY_PATH'] = os.getenv('LD_LIBRARY_PATH', '') + ':' + sys.prefix + '/lib'
nab_exe = os.path.join(sys.prefix, 'bin', '_nab')
commands = [nab_exe, ] + sys.argv[1:]
try:
    subprocess.call(commands)
except KeyboardInterrupt:
    pass
