#!/usr/bin/env python

import os
import sys
import subprocess

xleap_paths = ['prep', 'lib', 'parm', 'cmd']
os.environ['AMBERHOME'] = sys.prefix
os.environ['XENVIRONMENT'] = os.path.join(sys.prefix, 'dat', 'XaLeap_wcl')
include_paths = ['-I' + os.path.join(sys.prefix, 'dat', 'leap', path)
                 for path in xleap_paths]
xleap_exe = os.path.join(sys.prefix, 'bin', 'xaLeap')
commands = [xleap_exe,] + include_paths + sys.argv[1:]
try:
    subprocess.call(commands)
except KeyboardInterrupt:
    pass

